#define COMSIG_JS_OVERMAP_UPDATE "js_overmap_mark_dirty"
#define KM * 1000
#define JS_OVERMAP_TACMAP_SQUARE 2
#define JS_OVERMAP_TACMAP_TOTAL_SQUARES 26
#define JS_OVERMAP_TACMAP_TILE_SIZE JS_OVERMAP_TACMAP_SQUARE KM
#define JS_OVERMAP_TACMAP_SIZE JS_OVERMAP_TACMAP_TILE_SIZE * JS_OVERMAP_TACMAP_TOTAL_SQUARES
#define OVERMAP_FACTION_NANOTRASEN 1 << 0
#define OVERMAP_FACTION_SOLGOV 1 << 1
#define OVERMAP_FACTION_CIVILIAN 1 << 2
#define OVERMAP_FACTION_SYNDICATE 1 << 3
#define OVERMAP_FACTION_PIRATE 1 << 4
#define OVERMAP_FACTION_PLAYER OVERMAP_FACTION_NANOTRASEN | OVERMAP_FACTION_SOLGOV | OVERMAP_FACTION_CIVILIAN
#define IS_OVERMAP_JS_COLLISION_RESPONSE_ELIGIBLE(O) !istype(O, /datum/overmap/projectile)
#define IS_OVERMAP_JS_PROJECTILE(O) istype(O, /datum/overmap/projectile)

//Overmap damage types. Any kind of weapon you can think of goes here.
#define OVERMAP_DAMAGE_TYPE_KINETIC_SUBCAPITAL 1
#define OVERMAP_DAMAGE_TYPE_KINETIC_CAPITAL 2
#define OVERMAP_DAMAGE_TYPE_ENERGY 3
#define OVERMAP_DAMAGE_TYPE_EXPLOSIVE 4

#define THROW_NEW_NOTIMPLEMENTED_EXCEPTION CRASH("TODO: Not implemented!")

#define OVERMAP_INTERIOR_TYPE_CAPITAL 1
#define OVERMAP_INTERIOR_TYPE_TINY 2

#define OVERMAP_INTERIOR_METRIC_MOBS "mobs"
#define OVERMAP_INTERIOR_METRIC_Z_LEVELS "Zs"
#define OVERMAP_INTERIOR_METRIC_AREAS "areas"

#define ARMOUR_QUADRANT_NORTH_EAST 4
#define ARMOUR_QUADRANT_NORTH_WEST 3
#define ARMOUR_QUADRANT_SOUTH_WEST 2
#define ARMOUR_QUADRANT_SOUTH_EAST 1
//This ship is assigned to a chosen map layout. No need to load any interior.
#define OVERMAP_ROLE_PRIMARY 1
//This ship needs its interior loading in manually.
#define OVERMAP_ROLE_SECONDARY 2

#define OVERMAP_ARMOUR_THICKNESS_NONE 0
#define OVERMAP_ARMOUR_THICKNESS_LIGHT 250
#define OVERMAP_ARMOUR_THICKNESS_MEDIUM 500
#define OVERMAP_ARMOUR_THICKNESS_HEAVY 1000
#define OVERMAP_ARMOUR_THICKNESS_SUPER_HEAVY 1500
#define OVERMAP_ARMOUR_THICKNESS_ABLATIVE 2000
#define OVERMAP_ARMOUR_THICKNESS_GIGA 2500

///User has NO rights and may only observe the ship.
#define OVERMAP_CONTROL_RIGHTS_NONE 0
///User is able to steer the ship.
#define OVERMAP_CONTROL_RIGHTS_HELM 1 << 0
///User is able to fire the ship's weaponry.
#define OVERMAP_CONTROL_RIGHTS_GUNNER 1 << 1

#define OVERMAP_CONTROL_RIGHTS_FULL OVERMAP_CONTROL_RIGHTS_HELM | OVERMAP_CONTROL_RIGHTS_GUNNER
