#define COMSIG_JS_OVERMAP_UPDATE "js_overmap_mark_dirty"
#define KM * 1000
#define JS_OVERMAP_TACMAP_SQUARE 2
#define JS_OVERMAP_TACMAP_TOTAL_SQUARES 26
#define JS_OVERMAP_TACMAP_TILE_SIZE JS_OVERMAP_TACMAP_SQUARE KM
#define JS_OVERMAP_TACMAP_SIZE JS_OVERMAP_TACMAP_TILE_SIZE * JS_OVERMAP_TACMAP_TOTAL_SQUARES
#define OVERMAP_FACTION_NANOTRASEN 1 << 0
#define OVERMAP_FACTION_SOLGOV 1 << 1
#define OVERMAP_FACTION_CIVILIAN 1 << 2
#define OVERMAP_FACTION_SYNDICATE 1 << 3
#define OVERMAP_FACTION_PIRATE 1 << 4
#define OVERMAP_FACTION_PLAYER OVERMAP_FACTION_NANOTRASEN | OVERMAP_FACTION_SOLGOV | OVERMAP_FACTION_CIVILIAN
#define IS_OVERMAP_JS_COLLISION_RESPONSE_ELIGIBLE(O) !istype(O, /datum/overmap/projectile)
#define IS_OVERMAP_JS_PROJECTILE(O) istype(O, /datum/overmap/projectile)

//Overmap damage types. Any kind of weapon you can think of goes here.
#define OVERMAP_DAMAGE_TYPE_KINETIC_SUBCAPITAL 1
#define OVERMAP_DAMAGE_TYPE_KINETIC_CAPITAL 2
#define OVERMAP_DAMAGE_TYPE_ENERGY 3
#define OVERMAP_DAMAGE_TYPE_EXPLOSIVE 4

#define THROW_NEW_NOTIMPLEMENTED_EXCEPTION CRASH("TODO: Not implemented!")

#define OVERMAP_INTERIOR_TYPE_CAPITAL 1
#define OVERMAP_INTERIOR_TYPE_TINY 2

#define OVERMAP_INTERIOR_METRIC_MOBS "mobs"
#define OVERMAP_INTERIOR_METRIC_Z_LEVELS "Zs"
#define OVERMAP_INTERIOR_METRIC_AREAS "areas"
